// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightVersions from 'starlight-versions'

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      plugins: [
        starlightVersions({
          versions: [ {
              slug: '2.0',
            },{ slug: '1.0' }],
        }),
      ],
      // Site title
      title: 'Bizarre Binary Docs',
      // Site description
      description: `Welcome to Bizarre Binary, your trusted companion for exploring the vast expanse of space.`,
      defaultLocale: 'root',
      locales: {
        // English docs in `src/content/docs/en/`
        root: {
          label: 'English',
          lang: 'en',
        },
        fr: {
          label: 'French',
        },
      },
      logo: {
        src: './src/assets/Fav-icon.ico',
        // replacesTitle: false, // Hide the site title
      },

      sidebar: [
        // Autogenerated group
        {
          // Link group title
          label: 'Getting Started',
          // Directory of an autogenerate a group of links
          autogenerate: { directory: 'getting-started' },
        },

        // ... exiting autogenerated group
        // Internal link group
        {
          label: 'Cosmic Navigation', // Group title
          items: [
            { slug: 'cosmic-navigation/reading-star-charts-and-maps' }, // Uses doc frontmatter title
            { label: 'Plotting a Course Through Space', slug: 'cosmic-navigation/plotting-course-through-space' }, // Custom label
            'cosmic-navigation/dealing-with-gravity-and-orbit', // Shorthand, uses doc title
          ],
        },
        // External links
        { label: 'Spaceships and Rockets', link: 'https://www.nasa.gov/humans-in-space/spaceships-and-rockets/' }, // An external link to the NASA website.
        { label: 'Space Movie', link: 'https://en.wikipedia.org/wiki/Interstellar_(film)' },
      ],
    }),
  ],
});